version: 2.1

jobs:
  # build:
  #   working_directory: ~/circleci-python
  #   docker:
  #     - image: "circleci/python:3.8.3"
  #   steps:
  #     - checkout
  #     - run: python BMI_calc.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8.3"
    steps:
      - checkout
      - run: pytest test_BMI_calc.py

workflows:
  build_and_test:
    jobs:
      - test
      # - build
      # - test:
      #     requires:
      #       - build